### ISSUE TITLE
Performance on purging cache

### ISSUE THREAD

**Issue by stefanobaldo** [wandenberg/nginx-selective-cache-purge-module#10]
I started using [nginx-selective-cache-purge-module](https://github.com/wandenberg/nginx-selective-cache-purge-module) on a fresh new environment and 10 hours later my cache size is about __20G__ with __450k files__.

It worked like a charm on the beginning but the performance on purging cache was critically degraded and I am now experiencing a __15s response time__ for each purge request (each request purges only about __10-20 files__).

The pattern I am using for the selective process is a simple prefix pattern, like `foo*`.

Is this an expected behavior? Is my cache size too big? I am planning on having a lot more cache files on the next weeks. It should be a problem?

nginx version: openresty/1.11.2.2
built by gcc 4.9.2 (Debian 4.9.2-10)
built with OpenSSL 1.0.1t  3 May 2016
TLS SNI support enabled
configure arguments: --prefix=/usr/local/openresty/nginx --with-cc-opt=-O2 --add-module=../ngx_devel_kit-0.3.0 --add-module=../echo-nginx-module-0.60 --add-module=../xss-nginx-module-0.05 --add-module=../ngx_coolkit-0.2rc3 --add-module=../set-misc-nginx-module-0.31 --add-module=../form-input-nginx-module-0.12 --add-module=../encrypted-session-nginx-module-0.06 --add-module=../srcache-nginx-module-0.31 --add-module=../ngx_lua-0.10.7 --add-module=../ngx_lua_upstream-0.06 --add-module=../headers-more-nginx-module-0.32 --add-module=../array-var-nginx-module-0.05 --add-module=../memc-nginx-module-0.17 --add-module=../redis2-nginx-module-0.13 --add-module=../redis-nginx-module-0.3.7 --add-module=../rds-json-nginx-module-0.14 --add-module=../rds-csv-nginx-module-0.07 --with-ld-opt=-Wl,-rpath,/usr/local/openresty/luajit/lib --add-module=/nginx-selective-cache-purge-module --with-http_ssl_module

**Comment by wandenberg** [comment]
@stefanobaldo the way to select the files to be purged is a scan on the keys. So, if you have more keys it will take more time, but this performance is not expected. You should check the configuration of your Redis, specially if it is saving the database to disk. Check this first please.
(The scan is done in an async way, so it does not block your Nginx to respond the other requests. If I have to bet I would do in a configuration problem on your redis)

**Comment by stefanobaldo** [comment]
Actually I am using [Amazon ElastiCache for Redis](https://aws.amazon.com/elasticache/redis/), that is a managed instance. I will check if it supports fine tuning or disable RDB persistence at least. Anyway, if not, I can easily switch to a self-managed container with redis and try disabling persistence. I will let you know.

**Comment by stefanobaldo** [comment]
I have checked that my redis instance has no __AOF persistence__ enabled, just __RDB snapshots__ which I cannot disable in my [managed cache service](https://aws.amazon.com/elasticache/redis/). I can switch to a self-managed redis container, but I was looking at the code and found something that might be causing the performance issues.

`#define SCAN_DATABASE_COMMAND "SCAN %s COUNT 100"`

The module is using __SCAN__ to find the matching keys with a __fixed COUNT of 100__ per iteration.

In my scenario:

    > info keyspace
    # Keyspace
    db0:keys=16390,expires=1251,avg_ttl=39252388
    db1:keys=577461,expires=577461,avg_ttl=2353978134

(db1 is where (nginx-selective-cache-purge-module)[https://github.com/wandenberg/nginx-selective-cache-purge-module] is currently writing to.

I currently have __577461 keys__ on the database. If I try to do:

`SCAN 0 MATCH pattern 577461` (that would basically be the same as doing `KEYS pattern`) it returns my matching keys in __less than a sec__. I think that the number of __SCAN iterations__ might be causing the problem.

Does it make any sense to you?

**Comment by wandenberg** [comment]
Not too much, only if you are having network limitations. 
It is highly recommended to have the Redis on the same instance of Nginx to avoid network latency.
Also, increasing the number of `COUNT` will make your Redis busy for a longer time. Which can block other operations. The idea is to have small operations to have a good compromise between execution time and concurrent operations (read and write). But feel free to tune this value to something that works for you.

**Comment by stefanobaldo** [comment]
I agree. I was not expecting having any network limitations since both managed redis and nginx container are inside AWS infrastructure. Anyway, I've just launched a new redis container in the same host as nginx and disabled all persistence features. I am not connecting by socket but TCP connection, but I should have no considerable latency at all. Since I flushed the cache, things are fast now, but I will let you know what happened as soon as the cache will start growing. Thank you.

**Comment by stefanobaldo** [comment]
It took longer for the purging performance to start degrading, but now some requests is taking about 15 to 20 secs again. I currently have 500k keys and the purging processes occur during all the time. My NGINX and Redis is separated in 2 containers on a single host, so the network latency is near zero, but I still have TCP connections flowing between NGINX and Redis. Do you think that running NGINX and Redis on the same container and start using Unix Socket could change anything?

**Comment by stefanobaldo** [comment]
I started using nginx and redis on the same host/container connected by unix socket for almost a week. All performance problems seem to be gone. I am closing this issue. Thank you for your support! 👍
