### ISSUE TITLE
segfaults on reload

### ISSUE THREAD

**Issue by a-beresnev** [wandenberg/nginx-selective-cache-purge-module#12]
Hi,
there is a hard-to-find bug in the module leading to segfaults on nginx reloads. Here is what happens:
1. In https://github.com/wandenberg/nginx-selective-cache-purge-module/blob/master/src/ngx_selective_cache_purge_module_setup.c#L365:L366 master initialiezes a shared memory structure with local (not shared) addresses
2. These addresses are valid in all forked workers
3. On reload master reinitializes the shared memory struct with new (changed) addresses and forks new workers
4. Old workers may still be handling their last requests and see the new addresses in shared memory which are invalid to them
5. .. segmentation fault

**Comment by laurretang** [comment]
I found two kinds of segfault 
Do reload while some requests are servicing, the first segfault occours occasionally
1. nginx-selective-cache-purge-module-master/src/ngx_selective_cache_purge_module_sync.c:384
and after some minutes, alll nginx workers are hung, 
So i can do restart nginx, then the second segfault happened
2. nginx-selective-cache-purge-module-master/src/ngx_selective_cache_purge_module_redis.c:173

**Comment by wandenberg** [comment]
Fixed on changes: 12fca86, 02c96d9 and 4e64e9b
