### ISSUE TITLE
Add PURGE method example to the readme

### ISSUE THREAD

**Issue by szepeviktor** [wandenberg/nginx-selective-cache-purge-module#14]
Something like

```nginx
if ($request_method = PURGE) {
    selective_cache_purge_query "$uri";
}
```

**Comment by wandenberg** [comment]
There is no reason for use PURGE or any mandatory method, it is up to the admin decide the configuration details. I try to keep the README and the examples as simple as possible.
The important thing is to let clear that to delete a cache entry is necessary to use the `selective_cache_purge_query` directive.

**Comment by szepeviktor** [comment]
OK.
