### ISSUE TITLE
Redis question

### ISSUE THREAD

**Issue by szepeviktor** [wandenberg/nginx-selective-cache-purge-module#15]
What is the purpose of Redis in selective_cache_purge?

I see nginx caching goes to the disk.

Thank you.

**Comment by wandenberg** [comment]
Redis is used as a "database" to index the cache entries (file path, cache key, ...) and the module lookup on it when needs to delete a cache entry. This is how it is possible to delete entries using wildcards.

**Comment by szepeviktor** [comment]
I thought `proxy_cache_path /tmp/cache_zone levels=1:2 keys_zone=zone:10m inactive=10d max_size=100m;` nginx stores the cache file son disk and the zone in shared memory. So Redis was a question for me - based on the readme.
